# Generated by Django 2.0.2 on 2018-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Имя')),
                ('about', models.TextField(verbose_name='О персоне')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['name'],
            },
        ),
    ]
