# Generated by Django 2.0.2 on 2018-02-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='/', max_length=32),
            preserve_default=False,
        ),
    ]
